app = 'tragar-cms-1751043123'
primary_region = 'iad'

[build]

[env]
  DATABASE_PATH = "/app/data/tragar_cms.db"
  PHX_HOST = "tragar-cms-1751043123.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[mounts]
  source = "tragar_data"
  destination = "/app/data"
  initial_size = "1gb"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

